// lo3web/src/app/library/_components/FicCard/FicCard.tsx
'use client';

import { FicCardData } from '@/types/domain-models';
import styles from './card.module.css';
import { getTagsByField } from '@/app/library/_utils/filter-utils';
import Tag from '../Tag/Tag';
import { TagField } from '@/app/library/_types/filter-enums';

export default function FicCard({
    data,
    onTagClicked,
}: {
    data: FicCardData;
    onTagClicked: (tagType: TagField, tag: string) => void;
}) {
    const tagTypes = [TagField.Warning, TagField.Fandom, TagField.Ship, TagField.Character, TagField.Tag];
    const authors = data.fic.authors ?? ['Anonymous'];
    const rating = data.fic.rating[0];
    const complete = data.fic.complete ? '✅' : '❌';
    return (
        <div className={styles.container}>
            <div className={styles.header}>
                <div className='text-lg'>{rating}</div>
                <div className='text-lg'>{complete}</div>
                <div className={`${styles.title} text-base`}>
                    <div>
                        <a href={data.fic.link}>{data.fic.title}</a> by{' '}
                        {authors.map(author => (
                            <Tag
                                key={author}
                                label={author}
                                onTagClicked={() => onTagClicked(TagField.Author, author)}></Tag>
                        ))}
                    </div>
                </div>
            </div>
            <div>
                {tagTypes.map(tagType => {
                    const tags = getTagsByField(data.fic, tagType);
                    return !!tags?.length ? (
                        <TagsBlok key={tagType} tagType={tagType} tags={getTagsByField(data.fic, tagType)}></TagsBlok>
                    ) : null;
                })}
                <span>
                    <strong>Words: </strong>
                    {data.fic.words}
                </span>
            </div>
        </div>
    );
    function TagsBlok({ tagType, tags }: { tagType: TagField; tags: string[] }) {
        return (
            <div>
                <span>
                    <strong>{tagType + 's: '}</strong>
                </span>
                {tags?.map(tag => (
                    <Tag key={tag} label={tag} onTagClicked={() => onTagClicked(tagType, tag)} withCross={false}></Tag>
                ))}
            </div>
        );
    }
}

// lo3web/src/routes/(fics-cards-pages)/_components/FicCard.svelte
<script lang="ts">
    import Tag from '$lib/components/Tag.svelte';
    import { FicType, type FicCardData } from '$lib/types/domain-models';
    import * as Card from '$ui/card';
    import { TagField, TagInclusion } from '../_types/filter-enums';
    import { getTagsByField } from '../_utils/filter-utils';
    import { pageState } from './state.svelte';

    const { cardData }: { cardData: FicCardData } = $props();
    const tagTypes = [TagField.Warning, TagField.Fandom, TagField.Ship, TagField.Character, TagField.Tag];
    const authors = cardData.fic.authors ?? ['Anonymous'];
</script>

<Card.Root>
    <Card.Header>
        <Card.Title class="text-base">
            <a href={cardData.fic.link}>{cardData.fic.title}</a>
        </Card.Title>
        <Card.Description
            >{cardData.key.ficType.toLowerCase()} by {#each authors as author}
                <Tag
                    label={author}
                    onclick={() => pageState.withTagFilter(TagField.Author, TagInclusion.Include, author)}
                ></Tag>
            {/each}
        </Card.Description>
    </Card.Header>
    <Card.Content>
        {#each tagTypes as tagField}
            {@const tags = getTagsByField(cardData.fic, tagField)}
            {#if tags.length}
                <div>
                    <span class="font-semibold">{tagField + 's: '}</span>
                    {#each tags as tag}
                        <Tag
                            label={tag}
                            withCross={false}
                            onclick={() => pageState.withTagFilter(tagField, TagInclusion.Include, tag)}
                        ></Tag>
                    {/each}
                </div>
            {/if}
        {/each}
    </Card.Content>
    <Card.Footer class="flex justify-between">
        <div class="flex gap-2">
            <div>{cardData.fic.rating[0]}</div>
            {#if !cardData.fic.complete}
                <div>❌</div>
            {/if}
            {#if cardData.details.spicy}
                <div>🔥</div>
            {/if}
        </div>

        <div>Words: {cardData.fic.words.toLocaleString('en-us')}</div>
    </Card.Footer>
</Card.Root>

<style></style>
